export const specializationsWithSlots = [
  { id: 20, specialization: 'Anesthesiology', slot: 20 },
  { id: 4, specialization: 'Cardiology', slot: 45 },
  { id: 5, specialization: 'Dermatology', slot: 20 },
  { id: 12, specialization: 'Endocrinology', slot: 20 },
  { id: 13, specialization: 'Gastroenterology', slot: 20 },
  { id: 1, specialization: 'General Medicine', slot: 20 },
  { id: 18, specialization: 'General Surgery', slot: 60 },
  { id: 3, specialization: 'Gynecology and Obstetrics', slot: 30 },
  { id: 19, specialization: 'Internal Medicine', slot: 45 },
  { id: 16, specialization: 'Nephrology', slot: 30 },
  { id: 8, specialization: 'Neurology', slot: 45 },
  { id: 17, specialization: 'Oncology', slot: 60 },
  { id: 6, specialization: 'Ophthalmology', slot: 20 },
  { id: 7, specialization: 'Otorhinolaryngology', slot: 20 },
  { id: 2, specialization: 'Pediatrics', slot: 20 },
  { id: 14, specialization: 'Pneumology', slot: 20 },
  { id: 9, specialization: 'Psychiatry', slot: 20 },
  { id: 15, specialization: 'Rheumatology', slot: 20 },
  { id: 10, specialization: 'Traumatology and Orthopedics', slot: 20 },
  { id: 11, specialization: 'Urology', slot: 20 },
];